model_config:
  model_type: "decoder_only"
  n_layers: 6
  d_model: 512
  n_heads: 8
  seq_len: 512
  d_hidden: 2048
  drop_prob1: 0.2
  drop_prob2: 0.4

training_config:
  batch_size: 32
  learning_rate: 0.0001
  num_epochs: 200
  weight_decay: 0.001

data_config:
  dataset_name: "custom_dataset"
  chunk_size: 512
  vocab_size: 32000
  max_seq_length: 512

device_config:
  device: "cuda"
  num_gpus: 1